### ISSUE TITLE
Add a way to set custom request parameters

### ISSUE THREAD

**Issue by ddeboer** [caseyamcl/phpoaipmh#19]
Such as an API key.

**Comment by caseyamcl** [comment]
Hi @ddeboer .. This sounds like a useful feature request.  Can you, however, give me an example of an OAI endpoint that uses custom params?

**Comment by caseyamcl** [comment]
Hi @ddeboer, I've been reading the OAI docs and mulling this.  I think the best way to accomplish this is to use Guzzle request event listeners.  As an example, if you want to add an "api_key" query parameter (or make any other modifications to the request before it is sent):

```php
$guzzleAdapter = new \Phpoaipmh\HttpAdapter\Guzzle();
$guzzleAdapter->getGuzzleClient()->getEmitter()->on('before', function(\GuzzleHttp\Event\BeforeEvent $event) {
   $req = $event->getRequest();
   $req->getQuery()->add('api_key', 'xyz123');

   // You could do other things to the request here, too, like adding a header..
   $req->addHeader('Some-Header', 'some-header-value');
});

$client  = new \Phpoaipmh\Client('http://some.service.com/oai', $guzzleAdapter);
```
