### ISSUE TITLE
Load XML with local NS

### ISSUE THREAD

**Issue by vbeauvivre** [caseyamcl/phpoaipmh#26]
Hi, I try to use your client which simple but smart anp powerful, Thx for it !

I having problem trying to harvest data from http://oai.bnf.fr/oai2/OAIHandler?verb=ListSets
This repository provides XML with local namespace like this :
````
<set>
  <setSpec>gallica:typedoc:monographies</setSpec>
  <setName>Gallica : types de documents : monographies imprimées</setName>
  <setDescription>
    <oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
      <dc:description xml:lang="fre">Cet ensemble donne accès aux ouvrages imprimés de Gallica.</dc:description>
      <dc:description xml:lang="eng">This set provides access to the printed books in Gallica.</dc:description>
    </oai_dc:dc>
  </setDescription>
</set>
````

I tried this fix [https://github.com/naoned/phpoaipmh/commit/f6af6588aad16803d13c14a143f78952fba93886] and it works for me but I saw you did the other way for bug fixing [https://github.com/caseyamcl/phpoaipmh/commit/87d70d371fc666dd1b35c4058a9fd15974403207]. Can you tell me more about this bug, in order to fix it in a more generic way ?
I will provide a pull request wen I’m done.

**Comment by nderambure** [comment]
Hi, what's your problem exactly ?
Because I've done same thing on another OAI deposit and I can see that the root element lacks of the namespace : xmlns="http://www.openarchives.org/OAI/2.0/".
Here is an example of what I request : 
http://cocoon.huma-num.fr/crdo_servlet/oai-pmh?verb=GetRecord&identifier=oai:crdo.vjf.cnrs.fr:crdo-FRA_ESLO_omelette131_SOUND&metadataPrefix=olac

By the way, thx to the contributors and owner of this project, it works great ;)

**Comment by vbeauvivre** [comment]
I tried to reduce the problem to it simplest, and I realised 
````
        $url = 'http://oai.bnf.fr/oai2/OAIHandler';
        $client = new \Phpoaipmh\Client($url);
        $endPoint = new \Phpoaipmh\Endpoint($client);
        foreach ($endPoint->listSets() as $set) {
            var_dump($set);
        };
````
It works fine in a plain PHP file, but fails in my Symfony fullstack app, with message ````Warning: SimpleXMLElement::__construct(): namespace error : Namespace prefix xsi for schemaLocation on dc is not defined````
My php.ini error reporting is on E_ALL so I don’t undersand why the warning dos not appear in cli. It’s maybe a problem with SimpleXML config. I try to go further.

**Comment by vbeauvivre** [comment]
I finally got it. Here is my bug explanation
My full XML :
````
<OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<responseDate>2015-06-29T14:45:35Z</responseDate>
<request verb="ListSets">http://oai.bnf.fr/oai2/OAIHandler</request>
<ListSets>
<set>
  <setSpec>gallica:typedoc:monographies</setSpec>
  <setDescription>
    <oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
      <dc:description xml:lang="fre">Cet ensemble donne accès aux ouvrages imprimés de Gallica.</dc:description>
    </oai_dc:dc>
  </setDescription>
</set>
…
````
BUT, it tries to create XML with this content 
````
<set>
  <setSpec>gallica:typedoc:monographies</setSpec>
  <setDescription>
    <oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
      <dc:description xml:lang="fre">Cet ensemble donne accès aux ouvrages imprimés de Gallica.</dc:description>
    </oai_dc:dc>
  </setDescription>
</set>
````

So XSI has been «lost», that’s why simpleXMLElement construct fails. See fix proposal in PR.

**Comment by nderambure** [comment]
Well, in fact, I have the same warning :)

**Comment by vbeauvivre** [comment]
What about my proposal here : #27 ?
I didn’t find another way to define namespaces but with include it in XML string …

**Comment by caseyamcl** [comment]
This has been resolved in the latest version :)
