### ISSUE TITLE
The oaiUrl in the example is no longer valid

### ISSUE THREAD

**Issue by netsensei** [caseyamcl/phpoaipmh#33]
Hi,

The example CLI app included in the package does no longer work. The `$oaiUrl` is pointing to http://nsdl.org/oai but that URL redirects to https://nsdl.oercommons.org. 

Does the NSDL still provide an active OAI endpoint?

**Comment by caseyamcl** [comment]
Hi, @netsensei Good catch.  It looks like NSDL discontinued their OAI-PMH service, so I've updated the URL to http://openscholarship.wustl.edu/do/oai/.

The commit was made; I'll tag a new release tomorrow.
