### ISSUE TITLE
Minor mistake in readme.md?

### ISSUE THREAD

**Issue by Nauhaie** [caseyamcl/phpoaipmh#34]
It appears that in the file readme.md, the line 

$guzzleAdapter = new \Phpoaipmh\HttpAdapter\Guzzle();

should be replaced with

$guzzleAdapter = new \Phpoaipmh\HttpAdapter\GuzzleAdapter();

Am I wrong? Thanks

**Comment by caseyamcl** [comment]
Hi @Nauhaie .. Thank you for the correction!  I've just had a chance to start working on this repo again, and I am going through tickets.  You were right, and it has been corrected.
