### ISSUE TITLE
Resumption Token

### ISSUE THREAD

**Issue by mtw28** [caseyamcl/phpoaipmh#37]
Is it possible to view the current resumption token as the iterator runs?

Then would it be possible to add a new param for a resumption token in the listRecords function?

The idea is to split harvesting a large set into multiple runs of a script.

**Comment by sblommaert** [comment]
I've already added a pull request to do this. https://github.com/caseyamcl/phpoaipmh/pull/36
Let's hope it will be added!

**Comment by caseyamcl** [comment]
Pull request https://github.com/caseyamcl/phpoaipmh/pull/36 was merged, and I have just released https://github.com/caseyamcl/phpoaipmh/releases/tag/v2.5, which solves this issue.

Thanks for your patience, and enjoy :)
