### ISSUE TITLE
Replace references to `DateTime` with `DateTimeInterface`

### ISSUE THREAD

**Issue by caseyamcl** [caseyamcl/phpoaipmh#49]
We still (unofficially) support PHP v5.4 in Version 2.x of phpoaipmh, but will not do so in v3.

At that point, we can replace all references to `DateTime` with `DateTimeInterface`, which became available in PHP v5.5.

**Comment by rudolfbyker** [comment]
This would be fantastic, since I'm using `DateTimeImmutable` instead of `DateTime`, which gives me incorrect "Deprecated" errors. The `createRecordIterator` function seems to assume that anything that is not `\DateTime` is a `string`.

**Comment by caseyamcl** [comment]
Hi @rudolfbyker .. This is resolved in v3.  [Release notes](https://github.com/caseyamcl/phpoaipmh/releases/tag/v3.0) Enjoy!

**Comment by rudolfbyker** [comment]
Awesome, thanks!
