### ISSUE TITLE
can't get element values inside metadata

### ISSUE THREAD

**Issue by saravanandos** [caseyamcl/phpoaipmh#52]
When i am using your example its show all.But not showing values inside metadata its showing header values only.
$recs = $myEndpoint->listRecords('oai_dc');

foreach($recs as $rec) {
    var_dump($rec);
}
The above code only shows the header values.If i tried to do like `var_dump($rec->metadata)`(attached output below)
![var_dumrecmetadata](https://user-images.githubusercontent.com/15042149/50053819-19d72200-0133-11e9-8d45-b8ae9c5597e1.PNG)
Normal output
![vardumprec](https://user-images.githubusercontent.com/15042149/50053820-1a6fb880-0133-11e9-821f-c7b07e0d0106.PNG)

then it return empty values.How can i get the values inside metadata element.

**Comment by saravanandos** [comment]
Finally i solved it

**Comment by pedrosanta** [comment]
Hi @saravanandos, how did you solve it? I'm getting a similar behaviour.

**Comment by zwok** [comment]
@saravanandos. please provide the solution you found. Thank you!
