### ISSUE TITLE
Support getTotalRecordCount for queries without resumption tokens

### ISSUE THREAD

**Issue by asmecher** [caseyamcl/phpoaipmh#55]
Currently `RecordIterator::getTotalRecordCount` will return `null` in two cases:
- When the `ResumptionToken` from the repository does not contain/support `completeListSize`, or
- If the list is short enough to not contain a `ResumptionToken` (i.e. the complete batch is sent all at once).

When a complete batch is sent all at once, the total record count should be ascertained by counting the number of items in the batch.

**Comment by asmecher** [comment]
I see there was a test case specifically to ensure that single-page lists returned `null` from `getTotalRecordCount` -- but I think this is more useful. I've adjusted the tests to cover this case and they run successfully.

**Comment by caseyamcl** [comment]
Merged!  Thanks for your contribution @asmecher . I'll be releasing a new version with this functionality (and a few other cleanups) today.

**Comment by asmecher** [comment]
Thanks, @caseyamcl, my pleasure!
