### ISSUE TITLE
Retrieve full batch from RecordIterator

### ISSUE THREAD

**Issue by MarcoRemy** [caseyamcl/phpoaipmh#57]
Hi there. We harvest data from a public library with millions of records. This large amount of files isn't easy to handle. Would it be possible to return whole batches instead of single records?

**Comment by caseyamcl** [comment]
Hi @MarcoRemy,

I've released a new version ([v3.3](https://github.com/caseyamcl/phpoaipmh/releases/tag/v3.3)) that should make this possible.  For example, you can build your own custom iterator around batches :

```php
$itererator = new RecordIterator($client, $verb, $params);

while ($iterator->retrieveNextBatch() !== 0) {
    // Get the current batch
    $batch = $iterator->getBatch();

    // do something with each batch (it is an array of SimpleXML objects)...
}
```

FYI - I plan on releasing a complete PHP8-compatible rewrite of this library soon; not sure when it will be though, but it will be much more flexible.
