### ISSUE TITLE
PHP8 Deprecation errors

### ISSUE THREAD

**Issue by tikaszvince** [caseyamcl/phpoaipmh#61]
I'm using this library with [Drupal](https://www.drupal.org/) [OAI-PMH Harvester module](https://www.drupal.org/project/oai_pmh_harvester).
When I run a harvest action I got some PHP deprecation errors.

`Deprecated function: Return type of Phpoaipmh\RecordIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 33 of vendor/caseyamcl/phpoaipmh/src/RecordIterator.php).`

`Deprecated function: Return type of Phpoaipmh\RecordIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 33 of vendor/caseyamcl/phpoaipmh/src/RecordIterator.php).`

`Deprecated function: Return type of Phpoaipmh\RecordIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 33 of vendor/caseyamcl/phpoaipmh/src/RecordIterator.php).`

`Deprecated function: Return type of Phpoaipmh\RecordIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 33 of vendor/caseyamcl/phpoaipmh/src/RecordIterator.php).`

`Deprecated function: Return type of Phpoaipmh\RecordIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 33 of vendor/caseyamcl/phpoaipmh/src/RecordIterator.php).`

**Comment by tikaszvince** [comment]
I've created a pull request to fix this #62

**Comment by caseyamcl** [comment]
merged pull request; will release patch version, along with some other minor changes today. Thanks!
